<script setup lang="ts">
import { ref } from 'vue'
import { Braces, Play, WandSparkles } from 'lucide-vue-next'
import { createPlan, executePlan, type QueryPlan, type QueryResult } from '@/api/client'
const question=ref('');const plan=ref<QueryPlan>();const result=ref<QueryResult>();const busy=ref(false);const error=ref('')
async function planQuery(){busy.value=true;error.value='';result.value=undefined;try{plan.value=await createPlan(question.value)}catch(e){error.value=e instanceof Error?e.message:'计划生成失败'}finally{busy.value=false}}
async function execute(){if(!plan.value)return;busy.value=true;try{result.value=await executePlan(plan.value.plan_id)}catch(e){error.value=e instanceof Error?e.message:'执行失败'}finally{busy.value=false}}
</script>
<template><div class="query-layout"><section class="panel composer"><header><div><p class="kicker">NATURAL LANGUAGE</p><h2>查询意图</h2></div></header><label>描述要分析的成本问题<textarea v-model="question" rows="5" placeholder="例如：查看本月各服务成本趋势和异常增长"/></label><button data-testid="create-plan" class="primary-button" :disabled="question.length<3||busy" @click="planQuery"><WandSparkles :size="17"/>生成执行计划</button><p v-if="error" class="error-line" role="alert">{{error}}</p></section><section class="panel plan-pane"><header><div><p class="kicker">AUTHORIZED PLAN</p><h2>AST 与预算门禁</h2></div><span v-if="plan" class="badge" data-state="planned">{{plan.status}}</span></header><div v-if="!plan" class="plan-placeholder"><Braces :size="26"/><p>计划生成后，这里展示服务端 SQL 模板、AST 判定和预算。</p></div><template v-else><dl class="plan-facts"><div><dt>意图</dt><dd>{{plan.kind}}</dd></div><div><dt>AST</dt><dd>{{plan.ast_allowed?'只读通过':'拒绝'}}</dd></div><div><dt>预算</dt><dd>{{plan.estimated_cost}} / {{plan.budget_limit}}</dd></div></dl><pre>{{plan.statement}}</pre><button data-testid="execute-plan" class="primary-button" :disabled="!plan.ast_allowed||busy" @click="execute"><Play :size="17"/>执行已授权计划</button></template></section><section v-if="result" class="panel result-pane"><header><div><p class="kicker">PERSISTED RESULT</p><h2>查询结果</h2></div><span class="badge" :data-state="result.status">{{result.status}}</span></header><div class="result-scroll"><table><thead><tr><th v-for="key in Object.keys(result.page[0]??{})" :key="key">{{key}}</th></tr></thead><tbody><tr v-for="(row,index) in result.page" :key="index"><td v-for="key in Object.keys(row)" :key="key">{{row[key]}}</td></tr></tbody></table></div></section></div></template>
